# Generated by Django 4.2.6 on 2023-10-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("aired", models.TextField()),
                ("studios", models.TextField()),
                ("description", models.TextField()),
                ("img", models.TextField()),
                ("video", models.TextField()),
            ],
        ),
    ]
