# Generated by Django 4.2.6 on 2023-10-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AnimePlayApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField()),
            ],
        ),
    ]
